"""update database schema

Revision ID: 944650b8bd49
Revises: 
Create Date: 2024-08-21 14:34:14.646646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '944650b8bd49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['_id'])

    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['_id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['_id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['_id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['_id'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('time_created', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('friend_relation_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['_id'])
        batch_op.create_foreign_key(None, 'friend', ['friend_relation_id'], ['_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('friend_relation_id')
        batch_op.drop_column('time_created')
        batch_op.drop_column('day')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('image',
    sa.Column('_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('_id', name='image_pkey')
    )
    # ### end Alembic commands ###
